baseURL: https://dacio.dev/
languageCode: en-us
title: Dacio Romero
theme: hugo-coder
disqusShortname: dacio

permalinks:
  posts: /posts/:year/:month/:day/:slug/

params:
  author: Dacio Romero
  description: Just another Software Engineer's personal website.
  info: Full-stack Software Engineer
  gravatar: dacioromero@gmail.com
  keywords: blog,developer
  hideCredits: true
  since: 2019
  colorScheme: auto
  social:
    - name: GitHub
      icon: fa fa-github fa-2x
      url: https://github.com/dacioromero/
    - name: LinkedIn
      icon: fa fa-linkedin fa-2x
      url: https://www.linkedin.com/in/dacioromero/
    - name: Twitter
      icon: fa fa-twitter fa-2x
      url: https://twitter.com/dacioromero

menu:
  main:
    - name: Blog
      url: /posts/
